# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_AUTH_URI: ${{ secrets.GOOGLE_AUTH_URI }}
      GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Releaes  
      uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.21.8.linux-amd64.tar.gz"
        release_tag: "v0.1.0-alpha"
        overwrite: TRUE
        ldflags: -X "main.SpreadsheetId=${{ env.SPREADSHEET_ID}}" -X "sheetsFoodFinder/pkg/authhelper.ClientID=${{ env.GOOGLE_CLIENT_ID}}" -X "sheetsFoodFinder/pkg/authhelper.ClientSecret=${{ env.GOOGLE_CLIENT_SECRET}}" -X "sheetsFoodFinder/pkg/authhelper.AuthURL=${{ env.GOOGLE_AUTH_URI}}" -X "sheetsFoodFinder/pkg/authhelper.TokenURL=${{ env.GOOGLE_TOKEN_URI}}"    
